### PR TITLE
Add ranking system to set per-particle threshold for acceleration strength.

### PR DESCRIPTION
**Pull request by brb1031**
By recording and ranking recent acceleration strengths, a minimum
threshold (10th strongest) must be beat before the particle will
perform detailed calculations in reaction to another.  The acceleration
threshold and threshold rank update when the particle experiences too
many or too few interactions above its threshold.  For 44 Particles,
most particles seem to settle on 7th strongest influences.

### CODE REVIEW

**Comment by mcw0933** [comment]
:+1: Looks good!

**Comment by jakebrown58** [comment]
have we run any benchmarks with this branch against master in the 'alternate' mode with the asteroid belt?

**Comment by jakebrown58** [comment]
i ran benchmarks after fixing simulation when 'collissions on'.   ('the r key').

...I got a lower frames per second with these changes (15 versus 20) compared to master.

I'd like to isolate and find out what the slowness is coming from before merging.

**Comment by brb1031** [comment]
Re: Slowness.  The good news: the profiler takes almost no cpu time.  Bad news: It doesn't speed anything up.

**Comment by jakebrown58** [comment]
yes - that's true.  but my test was consistent between branches, and the number of collissions was negligible within my test window.   (test frame rate for 10 seconds, and go from 500 to 498 particles in both branches).

............i SUSPECT that the reason perf is going down is that we're actually doing a more robust integration, and not that your code is slower.  (IE - we're doing more work.  not we're doing the same work slower).

**Comment by brb1031** [comment]
I don't think the integration details have changed.  Same math, different implementation.  Even when turning off all the profiling code, and just having it do the same as it used to (with just Vector3d changes) is abysmal in asteroid version.  (0-2 FPS on my machine).

**Comment by jakebrown58** [comment]
let's give each other demos of how we're checking for FPS so we can compare methods.  i never see frame rates that low (unless there are JS errors getting thrown).

**Comment by jakebrown58** [comment]
you're right though - you didn't change integration specifically.  i was thinking about differences with a feature i'd had but removed called 'alwaysIntegrate'.  there's some residue from that still in the codebase.   basically it was a very powerful simplification where only the 10 most massive objects ever were integrated against.    it let us scale really well, and it works great for large-body systems.  but it made cloud collapse less realistic, because the particles didn't interact with each other and collapse.

**Comment by brb1031** [comment]
Rebasing off new master is not working out how I'd like, so I'm closing this.  If the feature is re-introduced, it'll be in a new branch.

**Pull request closed without merging**
