### PR TITLE
Make usage of z-axis ubiquitous.

### LINKED ISSUE #13: Trying a vector solution to simplify transition to 3d

### PR DESCRIPTION
**Pull request by brb1031**
Closes #13 

Particles now use a 3d vector for position, velocity and acceleration.  A tiny 3d vector library has been added that implements the 3d vector as a javascript array of length 3.

### CODE REVIEW

**Comment by brb1031** [comment]
@jakebrown58 Have a look?

**Comment by jakebrown58** [comment]
This introduces some bugs.  I locally fixed 2 of them, but I think the Array.prototype approach will have some bad side-effects.

The main reason comes down to in js, you can use hashing syntax the same as arrays as objects:

so:     
var obj = { 0: "bob" }
var x = obj[0];    // x is "bob"

and

var arr = bob"]
var x = arr[0];  // x is "bob"


On line 247 of the viewport, we use such a 'hashing' approach, and unfortunately, JS is getting confused whether the list is an array or an object.

sometimes 
  pair = "0" as it should and it works.
sometimes
  pair = "v_dot" and it throws an error.

....this manifests when you use the 'c' key, and you won't see any planets and a bunch of JS errors.

**Comment by jakebrown58** [comment]
I pushed the bug fixes up to your branch.

**Comment by jakebrown58** [comment]
....minus the bigger issue from the large comment.

**Comment by brb1031** [comment]
So, do you think this can be best solved by implementing all the position,vel,acc stuff as methods of the Particle class (rather than Array)?

**Comment by jakebrown58** [comment]
i won't have a strong opinion until i play around with it.

**Pull request merged**
